### ISSUE TITLE
Clean up package directory

### ISSUE THREAD

**Issue by etrombly** [etrombly/rust-crosscompile#5]
Currently package.sh doesn't clean the package directory before copying everything. There could be artifacts from a previous build there.

**Comment by ajmcmiddlin** [comment]
I believe this is now fixed, as `package` gets deleted if it exists. However, my preference would be to abort the build if it exists, so we don't accidentally delete unrelated data in the source directory. Then, move the delete to the end of the script after the zip has been produced. I can PR something if you want.

**Comment by etrombly** [comment]
I just moved the package directory deletion to the end. You may need to manually clean it up on any existing projects once. Thanks for the recommendation.
